version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: asia48-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: asia48db
      MYSQL_USER: asia48user
      MYSQL_PASSWORD: asia48password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - asia48-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      command: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]
    container_name: asia48-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Database configuration
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/asia48db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: asia48user
      SPRING_DATASOURCE_PASSWORD: asia48password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      
      # JPA/Hibernate configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      
      # Application configuration
      SPRING_PROFILES_ACTIVE: docker
      
      # JWT configuration (you may need to adjust these)
      JWT_SECRET: mySecretKey
      JWT_EXPIRATION: 86400000
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - asia48-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
    driver: local

networks:
  asia48-network:
    driver: bridge
